import { Inject, Injectable } from '@nestjs/common';
import { PG_CONNECTION } from 'src/constants';
import { IsUUID, IsEnum, IsDate, IsString, IsNotEmpty, Length, Matches, IsOptional } from 'class-validator';
import { Type } from 'class-transformer';

export enum BillingType {
  COMPANY = 'COMPANY',
  OUTLET = 'OUTLET',
}

export class BillingInfoEntity {
  id: string; // auto-generated by DB
  company_id: string;
  billing_type: BillingType;
  gstin: string;
  pan: string;
  billing_address_line1: string;
  billing_address_line2: string | null;
  city: string;
  state: string;
  pincode: string;
  state_code: string;
  bank_account_number: string | null;
  bank_ifsc: string | null;
  invoice_prefix: string | null;
  created_at: Date;
  updated_at: Date;
}

@Injectable()
export class BillingInfoRepositoryService {

    private createBillingInfo = `
    INSERT INTO rito.billing_info (
        company_id,
        billing_type,
        gstin,
        pan,
        billing_address_line1,
        billing_address_line2,
        city,
        state,
        pincode,
        state_code,
        bank_account_number,
        bank_ifsc,
        invoice_prefix
    ) VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13
    ) RETURNING *;
`;

    constructor(@Inject(PG_CONNECTION) private conn: any) {}

    async create(billingInfoDto: Omit<BillingInfoEntity, 'id' | 'created_at' | 'updated_at'>) {
    const result = await this.conn.query(this.createBillingInfo, [
        billingInfoDto.company_id,
        billingInfoDto.billing_type,
        billingInfoDto.gstin,
        billingInfoDto.pan,
        billingInfoDto.billing_address_line1,
        billingInfoDto.billing_address_line2 ?? null,
        billingInfoDto.city,
        billingInfoDto.state,
        billingInfoDto.pincode,
        billingInfoDto.state_code,
        billingInfoDto.bank_account_number ?? null,
        billingInfoDto.bank_ifsc ?? null,
        billingInfoDto.invoice_prefix ?? null,
    ]);

    return result.rows?.[0];
}
}
