import { Inject, Injectable } from '@nestjs/common';
import { PG_CONNECTION } from 'src/constants';
import { Pool } from 'pg'
import { IsNotEmpty, IsString, IsEmail, Length, IsDate, IsOptional } from 'class-validator';
import { Type } from 'class-transformer';

export class CompanyEntity {
  @IsOptional()
  @IsString()
  id: string; // UUID generated by DB

  @IsNotEmpty()
  @IsString()
  business_name: string;

  @IsNotEmpty()
  @IsEmail()
  email: string;

  @IsNotEmpty()
  @IsString()
  address_line1: string;

  @IsOptional()
  @IsString()
  address_line2: string;

  @IsNotEmpty()
  @IsString()
  city: string;

  @IsNotEmpty()
  @IsString()
  state: string;

  @IsNotEmpty()
  @IsString()
  @Length(6, 10) // Indian pincodes are 6 digits, but keeping a range
  pincode: string;

  @IsNotEmpty()
  @IsString()
  @Length(10, 15) // phone number length validation
  phone_number: string;

  @IsNotEmpty()
  @IsString()
  fssai_license_number: string;

  @IsNotEmpty()
  @IsString()
  trade_name: string;

  @IsNotEmpty()
  @IsString()
  owner: string;

  @IsNotEmpty()
  @IsString()
  @Length(10, 10) // Indian PAN is 10 characters
  pan: string;

  @IsNotEmpty()
  @Type(() => Date)
  @IsDate()
  created_at: Date;

  @IsNotEmpty()
  @Type(() => Date)
  @IsDate()
  updated_at: Date;
}

@Injectable()
export class CompanyRepositoryService {
    constructor(@Inject(PG_CONNECTION) private conn: Pool) {}
    private createCompany = `
        INSERT INTO rito.company (
            business_name,
            email,
            address_line1,
            address_line2,
            city,
            state,
            pincode,
            phone_number,
            fssai_license_number,
            trade_name,
            owner,
            pan
        ) VALUES (
            $1,
            $2,
            $3,
            $4, 
            $5,
            $6,
            $7,
            $8,
            $9,
            $10,
            $11,
            $12
        ) RETURNING *;
    `

    // testing
    private getAllCompanies = `
        SELECT
            id,
            business_name,
            email,
            address_line1,
            address_line2,
            city,
            state,
            pincode,
            phone_number,
            fssai_license_number,
            trade_name,
            owner,
            pan,
            created_at,
            updated_at
        FROM rito.company
    `

    async create(companyEntity: Omit<CompanyEntity, 'id' | 'created_at' | 'updated_at'>) {
        const result = await this.conn.query<CompanyEntity>(this.createCompany, [
            companyEntity.business_name,
            companyEntity.email,
            companyEntity.address_line1,
            companyEntity.address_line2,
            companyEntity.city,
            companyEntity.state,
            companyEntity.pincode,
            companyEntity.phone_number,
            companyEntity.fssai_license_number,
            companyEntity.trade_name,
            companyEntity.owner,
            companyEntity.pan
        ])

        return result.rows?.[0];
    }

    async getAllCompaniesTest() {
        const result = await this.conn.query(this.getAllCompanies)
        return result.rows
    }
    
}
